version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "viajepro-cloud-admin-dev"
s3_prefix = "viajepro-cloud-admin-dev"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
parameter_overrides = "Stage=\"dev\""